pmflib 6.0

diff --git a/preinstall-hook b/preinstall-hook
--- a/preinstall-hook
+++ b/preinstall-hook
@@ -3,15 +3,15 @@
 # ------------------------------------------------------------------------------
 # update revision number
 _PWD=$PWD
-if ! [ -d src/projects/pmflib/5.0 ]; then
-    echo "src/projects/pmflib/5.0 - not found"
+if ! [ -d src/projects/pmflib/6.0 ]; then
+    echo "src/projects/pmflib/6.0 - not found"
     exit 1
 fi
 
 # generate PMFLib version information -
 _PWD=$PWD
-cd src/projects/pmflib/5.0 || exit 1
+cd src/projects/pmflib/6.0 || exit 1
 ./UpdateGitVersion activate || exit 1
-VERS="5.`git rev-list --count HEAD`.`git rev-parse --short HEAD`"
+VERS="6.`git rev-list --count HEAD`.`git rev-parse --short HEAD`"
 cd $_PWD
 
